name: Update License Year

on:
  schedule:
    - cron: '0 0 1 1 *'  # Run at midnight on January 1st
  workflow_dispatch:  # Allow manual trigger
  
jobs:
  update-year:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Update copyright year
        run: |
          CURRENT_YEAR=$(date +%Y)
          sed -i "s/Copyright [0-9]\{4\}/Copyright $CURRENT_YEAR/" LICENSE
  
        # Commit all changed files back to the repository
      - name: Commit Updated License
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          body: "Automated update of copyright year in LICENSE file"
          commit_options: '--no-verify'
          file_pattern: 'LICENSE'
          commit_message: "Update copyright year to ${{ env.CURRENT_YEAR }}"
          # Optional commit user and author settings
          commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
          commit_user_email: my-github-actions-bot@example.org # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: Author <actions@github.com> # defaults to "username <numeric_id+username@users.noreply.github.com>", where "numeric_id" and "username" belong to the author of the commit that triggered the run
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}